name: Docker Image FaspImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - 'RELEASE-**'
  create:
    branches:
      - 'RELEASE-**'
env:
  RELEASE: startsWith(github.ref_name, 'RELEASE-**')
  
jobs:

  build-master:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo '::set-output name=TAG::${{ github.sha }}'
        docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
      id: TAG
  build-release:
    if: ${{ startsWith(github.ref_name, 'RELEASE-') }}
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.TAG.outputs.TAG}}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo '::set-output name=TAG::${{ github.ref_name }}'
        docker build . --file Dockerfile --tag my-image-name:${{ github.ref_name }}
      id: TAG
  Update-Infra:
    needs: build-release
    runs-on: ubuntu-latest 
    steps:
    - name: Update REPO
      uses: actions/checkout@v3
      with:
        repository: moncete/faspi-canary
    - name: TEST
      run: |
        echo ${{ needs.build-release.outputs.tag }}
        sed -i 's/faspi:.*/faspi:${{ needs.build-release.outputs.tag }}'
        cat rollout-canary.yaml
