name: Docker Image FaspImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - 'RELEASE-**'
  create:
    branches:
      - 'RELEASE-**'
env:
  RELEASE: startsWith(github.ref_name, 'RELEASE-**')
  
jobs:

  build-master:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
  build-release:
    if: ${{ startsWith(github.ref_name, 'RELEASE-') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.ref_name }}
    - uses: action/checkout@v3
    - name: Update REPO
      with:
        repository: https://github.com/moncete/faspi-canary.git
        path: .
    - name: TEST
      run: cat rollout-canary.yaml
    
      
